### ISSUE TITLE
Use $HOME and repo name (available as variable) to not hardcode either

### ISSUE THREAD

**Issue by larsvilhuber** [ledwindra/continuous-integration-stata#1]
https://github.com/ledwindra/continuous-integration-stata/blob/52d1768e10e048fa9cd5a1e7fd4a482612cb947a/.github/workflows/main.yml#L65

That would make it completely general.

**Comment by ledwindra** [comment]
Hi @larsvilhuber,

Thanks! It's fixed and tested. Additional environment variables include:
- HOME_DIR: full path of the home directory inside the Linux kernel
- REPOSITORY: the corresponding repository name
