### ISSUE TITLE
CI workflow is successful, even if Stata exits with an error

### ISSUE THREAD

**Issue by EBoisseauSierra** [ledwindra/continuous-integration-stata#9]
The workflow is successful (:heavy_check_mark:), even if `main.do` run raises an error.

## Expected results

When running Stata code yielding an error (cf. examples below), the CI workflow should fail (:x:).

Examples of such erroneous code include:

```stata
exit 42
```
or 

```stata
gen my_var = `undefined_macro'
local undefined_macro = "too late"
```
## Actual results

However, when running the CI workflow on such code, GH actions considers it as successful (:heavy_check_mark:).

Indeed, [running Stata in batch mode](https://github.com/ledwindra/continuous-integration-stata/blob/v1/entrypoint.sh#L34-L43) always exits with `0`, even if the code raised an error. This makes that the entry-point scripts always (implicitly) exits successfully, as no non-0 exit code is defined.

### How to reproduce the bug

1. Use one of the examples above as content of your `main.do`,
2. Run CI on it,
3. Notice how it succeed, despite the code raising an error.

### Environment

- workflow version: `v1`

**Comment by ledwindra** [comment]
Hi @EBoisseauSierra 

Thank you so much for this. Just to clarify, this has been resolved in your [PR,](https://github.com/ledwindra/continuous-integration-stata/pull/10) right? If so I'll merge and close this issue

**Comment by EBoisseauSierra** [comment]
Yes indeed: I've tried to separate the issue from my take on how to address it.

I tried to link them both using the [magic keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) but it didn't seem to work — perhaps because it was in an edit… anyway, this issue can be closed once the PR is merged.

**Comment by ledwindra** [comment]
Looks good, thanks! It's been merged to the main branch already. Hopefully you find this package useful 😀

**Comment by ledwindra** [comment]
Hi @EBoisseauSierra, you might want to run [Stata via Docker](https://github.com/ledwindra/docker-stata):
- Stata only: https://hub.docker.com/r/ledwindra/base-stata
- Stata with Jupyter: https://hub.docker.com/r/ledwindra/jupyter-stata

Let me know what you think if interested. Thanks!

**Comment by EBoisseauSierra** [comment]
Kudos! I was actually looking at setting up my own image, so GH Actions don't have to install Stata every time — so thanks a lot for your work!

**Comment by EBoisseauSierra** [comment]
I'm not sure here's the best place to discuss it, but anyway:

* Thanks again for putting this together — it makes much more sense that downloading the archive from Dropbox every time!
* I have adapted your image definition — see [my fork](https://github.com/EBoisseauSierra/docker-stata/tree/ebosi). The main changes are:
  * (Drop the Jupyter/LaTeX version I don't need)
  * Have an empty `/usr/local/stata/stata.lic` file already created. Indeed, I had trouble when I wanted to `echo >` or `touch` it during the CI workflow (more on that below).
* I have then create [my own image](https://hub.docker.com/r/eboisseausierra/stata) — I understand each one should do that with their own Stata archive (i.e. I gather your [`ledwindra/base-stata`](https://hub.docker.com/r/ledwindra/base-stata) uses Stata 15, whereas mine has Stata 17 installed). That's something that would prevent having something really scalable — unless one publishes multiple `stata-<version_no>` images. (Out of topic comment: the image is quite big (2.8 GB in my case), I'm wondering whether using [`alpine`](https://hub.docker.com/_/alpine) as base image would help.
* The above has enable me to greatly simplify the CI definition — cf. [my fork](https://github.com/EBoisseauSierra/continuous-integration-stata/tree/main_ebosi). The main changes are:
  * [Simplify the Dockerfile](https://github.com/EBoisseauSierra/continuous-integration-stata/blob/8508f32b7ce2faf66b6a7552683711c571a528a0/Dockerfile#L2), as everything has been already been pre-installed on the image.
  * [Simplify the args](https://github.com/EBoisseauSierra/continuous-integration-stata/blob/8508f32b7ce2faf66b6a7552683711c571a528a0/action.yml#L15-L17), as — because we don't use the interactive CLI install — we can pass the content of the licence file [in one go](https://github.com/EBoisseauSierra/continuous-integration-stata/blob/8508f32b7ce2faf66b6a7552683711c571a528a0/action.yml#L5-L7). Only 2 args/secrets are now required.
  * [Simplify how Stata is run](https://github.com/EBoisseauSierra/continuous-integration-stata/blob/8508f32b7ce2faf66b6a7552683711c571a528a0/entrypoint.sh#L6), as [this isn't DRY](https://github.com/ledwindra/continuous-integration-stata/blob/main/entrypoint.sh#L34-L43). The only issue is that the user input (the GH secret) isn't sanitised before execution — I might expand on that a little.
  
I'm not quite sure what is the best way forward now: I believe that using a Docker image with Stata pre-installed is a good thing as it improves the CI process, yet this requires some non-trivial pre-requisite from the user (publishing a Docker image with their own Stata version installed on it). So I'm not sure how much of these changes you'd like to port to your GH Actions plugin.

**Comment by ledwindra** [comment]
Hi it looks like you want to create an issue to my [docker-stata](github.com/ledwindra/docker-stata/) repository instead of this? File an issue there please
